services:

  server:
    entrypoint: /app/entrypoint.sh
    extends:
      file: docker-compose.common.yml
      service: server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  backup_cron:
    entrypoint: /app/entrypoint.sh
    environment:
      MODE: backup_cron
      BACKUP_CRON_SCHEDULE: 0 0 * * 4-6  # Every Friday, Saturday, Sunday at midnight
    extends:
      file: docker-compose.common.yml
      service: server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  client:
    extends:
      file: docker-compose.common.yml
      service: client
      target: build

  db:
    extends:
      file: docker-compose.common.yml
      service: db
    networks:
      - default

volumes:
  db_home:

networks:
  default:
    driver: bridge
