services:

  server:
    extends:
      file: docker-compose.common.yml
      service: server
    volumes:
      - ./server/src:/app/src
      - ./server/main.py:/app/main.py

  client:
    build:
      target: dev
    extends:
      file: docker-compose.common.yml
      service: client
    volumes:
      - ./frontend/src:/app/src

  db:
    extends:
      file: docker-compose.common.yml
      service: db

volumes:
  db_home:

networks:
  default:
    driver: bridge
