version: '3.7'

services:

  server:
    logging:
      options:
        max-size: "10m"
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - MIGRATE_ON_START=true
      - SQLALCHEMY_DB_URI=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./server/.env:/app/.env
    ports:
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  client:
    logging:
      options:
        max-size: "10m"
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - default

  db:
    logging:
      options:
        max-size: "10m"
    image: postgres:14-alpine
    user: postgres
    platform: linux/amd64
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5442:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_home:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db_home:

networks:
  default:
    driver: bridge
