version: '3.7'

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - MIGRATE_ON_START=true
      - SQLALCHEMY_DB_URI=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "9001:9001"

  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  db:
    image: postgres:14-alpine
    user: postgres
    platform: linux/amd64
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5442:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_home:/var/lib/postgresql/data

volumes:
  db_home:
