version: '3.7'

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - MIGRATE_ON_START=true
      - SQLALCHEMY_DB_URI=postgresql://postgres:postgres@db:5432/postgres

  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  db:
    image: postgres:14-alpine
    user: postgres
    platform: linux/amd64
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5442:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_home:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   - CERTBOT_EMAIL=youremail@gmail.com
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/certs:/etc/nginx/certs
      # - letsencrypt:/etc/letsencrypt
    depends_on:
      - server
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

volumes:
  db_home:
