import {FlightState, FlightType, PayersType, PaymentMethod, TowType} from "../lib/types.ts";

export const API_HOST = import.meta.env.VITE_API_HOST || 'http://localhost:9001';
export const DISABLE_CLOSING_ACTION = import.meta.env.VITE_DISABLE_CLOSING_ACTION == 'true';

export const CACHE_KEY_ACTION = 'action';
export const CACHE_KEY_ACTION_PAGE = 'actions_page';
export const CACHE_KEY_ACTION_PAGE_SIZE = 'actions_page_size';
export const CACHE_KEY_THEME = 'theme';
export const CACHE_KEY_REVIEW_MODE = 'review_mode';

export const TEXTS_HEBREW = {
    APP_NAME: "ניהול פעולת הדאיה",
    DASHBOARD: "לוח הטיסות",
    TOGGLE_THEME: "שנה צבע",
    CURRENT_ACTION: "הפעולה הנוכחית",
    SELECT_ACTION: "בחר פעולה",
    SELECT: "בחר",
    CANCEL: "ביטול",
    ACTION: "פעולה",
    CLICK_TO_SELECT: "לחץ לבחירה",
    FIELD_RESPONSIBLE: "אחראי בשדה",
    RESPONSIBLE_CFI: "מדריך אחראי",
    STATE: "שלב",
    GLIDER: "דאון",
    PILOT_1: "טייס ראשון או חניך",
    PILOT_2: "טייס שני או מדריך",
    TOW_AIRPLANE: "מטוס גורר",
    TOW_PILOT: "טייס גורר",
    TOW_TYPE: "גובה גרירה",
    NEW_FLIGHT: "טיסה חדשה",
    CREATE_FLIGHT: "צור טיסה חדשה",
    FLIGHT_TYPE: "סוג טיסה",
    PAYERS_TYPE: "סוג משלם",
    PAYMENT_METHOD: "אמצעי תשלום",
    DUPLICATE_FLIGHT: "שכפל טיסה",
    DELETE_FLIGHT: "מחק טיסה",
    DELETE_FLIGHT_CONFIRMATION: "האם אתה בטוח שברצונך למחוק את הטיסה?",
    DELETE_EVENT: "מחק אירוע",
    DELETE_EVENT_CONFIRMATION: "האם אתה בטוח שברצונך למחוק את האירוע?",
    PAYING_MEMBER: "חבר משלם",
    PAYMENT_RECEIVER: "מקבל תשלום",
    CONFIRM: "אישור",
    EDIT_FLIGHT: "ערוך טיסה",
    CLEAR: "נקה",
    ADVANCED_EDIT: "עריכה מתקדמת",
    CLEAR_CONFIRMATION: "האם אתה בטוח שברצונך לנקות את הטופס?",
    TAKE_OFF_TIME: "שעת ההמראה",
    LANDING_TIME: "שעת הנחיתה",
    DRAFT: "בהכנה",
    TOW: "בגרירה",
    INFLIGHT: "בטיסה",
    LANDED: "נחתה",
    DURATION: "משך",
    FLIGHT_STATE: "שלב טיסה",
    FLIGHT_STATES: "שלבי טיסה",
    FLIGHT_HAS_BUSY_ENTITIES_ALERT: "לא ניתן לשגר את הטיסה עד שהבאים מתפנים",
    CLICK_HERE_IF_NO_SECOND_PILOT: "לחץ כאן אם אין טייס שני",
    TOW_RELEASE_TIME: "שעת סיום הגרירה",
    ACTION_NOT_SELECTED_MESSAGE: "יש לבחור פעולה על מנת להתחיל.",
    ACTION_NOT_SELECTED_TITLE: "לא נבחרה פעולה",
    SELECT_TODAYS_ACTION: "בחר את הפעולה של היום",
    ACTIVE_TOW_AIRPLANES: "מטוסים גוררים פעילים",
    SELECT_TOW_PILOT: "בחר טייס גורר",
    ACTION_NOT_FULLY_CONFIGURED_TITLE: "נא להגדיר את הפעולה",
    ACTION_NOT_FULLY_CONFIGURED_MESSAGE: "יש להשלים את הגדרת הפעולה על מנת להתחיל",
    MISSING_CONFIGURATIONS: "הגדרות חסרות",
    NO_TOW_AIRPLANES_AVAILABLE: "אין מטוסים גוררים זמינים",
    TOW_AIRPLANE_NOT_AVAILABLE: "המטוס הגורר לא זמין",
    DISPATCH_FLIGHT: "שגר טיסה",
    SELECT_TOW_TYPE: "בחר גובה גרירה",
    SELF_LAUNCH: "המראה עצמאית ללא מטוס גורר",
    CLICK_HERE_IF_SELF_LAUNCH: "לחץ כאן אם הדאון ממריא עצמאית ללא מטוס גורר",
    CREW: "צוות",
    TOW_PILOT_CANNOT_TOW_HIMSELF: "לא ניתן לשבץ טייס גורר כגורר של עצמו",
    FLIGHTS: "טיסות",
    CANNOT_DEACTIVATE_TOW_AIRPLANE_DURING_TOW: "לא ניתן לעדכן מטוס גורר במהלך גרירה",
    CONFIRM_FLIGHT_STATE_CHANGE_TO_PREVIOUS: "האם אתה בטוח שברצונך להחזיר את הטיסה לשלב הקודם?",
    DEACTIVATE_TOW_AIRPLANE_CONFIRMATION: "האם אתה בטוח שברצונך להפסיק את הפעלת את המטוס הגורר?",
    UPDATE_RESPONSIBLE_CFI_CONFIRMATION: "האם אתה בטוח שברצונך לשנות את המדריך האחראי?",
    UPDATE_FIELD_RESPONSIBLE_CONFIRMATION: "האם אתה בטוח שברצונך לשנות את האחראי בשדה?",
    CLOSE_ACTION: "סגירת הפעולה",
    ACTION_CLOSED_TITLE: "הינך צופה בפעולה שנסגרה!",
    ACTION_CLOSED_MESSAGE: "יש לשים לב שמתאפשרת עריכת נתונים חלקית בלבד.",
    CLOSE_ACTION_CONFIRMATION: "האם אתה בטוח שברצונך לסגור את הפעולה?",
    CLOSE_ACTION_EVENT_CONFIRMATION: "האם ברצונך ליצור אירוע סגירה?",
    ID: "מספר זיהוי",
    DATE: "תאריך",
    WEEKDAY: "יום בשבוע",
    SUNDAY: "ראשון",
    MONDAY: "שני",
    TUESDAY: "שלישי",
    WEDNESDAY: "רביעי",
    THURSDAY: "חמישי",
    FRIDAY: "שישי",
    SATURDAY: "שבת",
    IS_CLOSED: "סגורה",
    YES: "כן",
    NO: "לא",
    CONFIRM_ACTION_CHANGE: "בבקשה אשר את שינוי הפעולה לפעולה הבאה",
    GO_TO_NEXT_PAGE: "עבור לעמוד הבא",
    GO_TO_PREVIOUS_PAGE: "חזור לעמוד הקודם",
    PAGE: "עמוד",
    FLIGHT_LANDED: "טיסה נחתה",
    FLIGHT_TOOK_OFF: "טיסה המריאה",
    FLIGHT_TOW_RELEASED: "סיום גרירה",
    ACTION_CLOSED: "הפעולה נסגרה",
    RESPONSIBLE_CFI_ASSIGNED: "מדריך אחראי הוקצה",
    RESPONSIBLE_CFI_UNASSIGNED: "מדריך אחראי הוסר",
    FIELD_RESPONSIBLE_ASSIGNED: "אחראי בשדה הוקצה",
    FIELD_RESPONSIBLE_UNASSIGNED: "אחראי בשדה הוסר",
    TOW_AIRPLANE_ACTIVATED: "מטוס גורר הופעל",
    TOW_AIRPLANE_DEACTIVATED: "מטוס גורר שוחרר",
    CREATED_AT: "זמן יצירה",
    TYPE: "סוג",
    AUTHOR: "יוצר",
    DATA: "נתונים",
    EVENTS: "אירועים",
    NOTIFICATIONS: "הודעות",
    RECIPIENT_NAME: "שם הנמען",
    RECIPIENT_EMAIL: "אימייל הנמען",
    SENT_AT: "זמן שליחה",
    STATUS: "סטטוס",
    FLIGHTSUMMARYFORPILOT: "סיכום הטיסה לטייס דאון",
    DAILYSUMMARYFOROBSERVER: "סיכום טיסות למפקח",
    SUMMARYFORTOWPILOT: "סיכום טיסות לטייס גורר",
    SUMMARYFORCFI: "סיכום טיסות למדריך",
    FLIGHTSEMAILREPORT: "דו״ח טיסות",
    HANDLED: "טופל",
    PENDING: "ממתין לטיפול",
    BEING_HANDLED: "בטיפול",
    SENT: "נשלח",
    FAILED: "נכשל",
    OPEN_SUMMARY_GENERATOR: 'הפקת דו״ח',
    GLIDER_PILOT: "טייס דאון",
    GENERATE_SUMMARY: 'הפקת דו״ח סיכום',
    REPORT_TYPE: 'סוג דו״ח',
    NUM_FLIGHTS: 'מספר טיסות',
    TOTAL_DURATION: 'זמן טיסה כולל',
    HOURS_MINUTES_SECONDS: 'שניות:דקות:שעות',
    CLOSE: 'סגור',
    SETTINGS: 'הגדרות',
    CONFIRM_ACTION_REOPEN: 'האם אתה בטוח שברצונך לפתוח מחדש את הפעולה?',
    REOPEN_ACTION: 'פתיחה מחדש של הפעולה',
    REOPEN_ACTION_EVENT_CONFIRMATION: 'האם ברצונך ליצור אירוע פתיחה מחדש?',
    EXPORT_ACTION_DATA: 'ייצוא נתוני הפעולה',
    IMPORT_REFERENCE_DATA: 'ייבוא נתונים',
    ACTION_DATA_EXPORTED_AT: 'נתוני הפעולה יוצאו בתאריך',
    ACTION_DATA_NOT_YET_EXPORTED: 'נתוני הפעולה טרם יוצאו',
    ACTION_REOPENED: 'הפעולה נפתחה מחדש',
    CONFIRM_ACTION_DATA_EXPORT: 'האם אתה בטוח שברצונך לבקש את ייצוא נתוני הפעולה?',
    CONFIRM_IMPORT_REFERENCE_DATA: 'האם אתה בטוח שברצונך לבקש ייבוא נתונים?',
    SETTLE_PAYMENT: 'הסדר תשלום',
    PAYMENT_BY_CLUB_MEMBER: 'לחץ כאן אם חבר מועדון משלם על הטיסה',
    FLIGHTS_WITH_UNSETTLED_PAYMENTS_TITLE: 'קיימות טיסות עם תשלומים שלא הוסדרו',
    FLIGHTS_WITH_UNSETTLED_PAYMENTS_MESSAGE: 'יש להסדיר את התשלומים על מנת לאפשר את סגירת הפעולה.',
    DRAFT_FLIGHTS: 'בהכנה',
    TOW_FLIGHTS: 'בגרירה',
    INFLIGHT_FLIGHTS: 'בטיסה',
    LANDED_FLIGHTS: 'נחתו',
    NO_FLIGHTS_IN_THIS_STATE: 'אין טיסות במצב זה',
    RESEND_NOTIFICATION: 'שלח מחדש',
    RESEND_NOTIFICATION_CONFIRMATION: 'האם אתה בטוח שברצונך לשלוח מחדש את ההודעה?',
    DATA_IMPORT_EXPORT_REQUEST_EVENTS: 'בקשות ייבוא וייצוא נתונים',
    NO_DATA_EXPORT_REQUEST_EVENTS_FOR_ACTION: 'אין בקשות ייצוא נתונים עבור הפעולה',
    ACTION_DATE: 'תאריך הפעולה',
    ACTION_EXPORTED_AT: 'נתוני הפעולה יוצאו בתאריך',
    SEND_EMAIL: "שליחה באימייל",
    SEND: "שלח",
    EMAIL_ADDRESS: "כתובת אימייל",
    CONFIRM_SEND_EMAIL: "האם אתה בטוח שברצונך לשלוח אימייל",
    SELECT_RECIPIENT: "בחר נמען",
    RECIPIENT: "נמען",
    EMAIL_SENT_SUCCESSFULLY: "האימייל נשלח בהצלחה",
    ERROR: "שגיאה",
    COMMENTS: "הערות",
    ADD_COMMENT: "הוסף הערה",
    CONTENT: "תוכן",
    NO_COMMENTS: "אין הערות",
    EDIT_COMMENT: "ערוך הערה",
    SAVE: "שמור",
    UPDATED_AT: "זמן עדכון",
    DELETE_COMMENT: "מחק הערה",
    DELETE_COMMENT_CONFIRMATION: "האם אתה בטוח שברצונך למחוק את ההערה?",
    MOVE_FLIGHT_TO_STATE: "העבר טיסה לשלב",
    ENTER_REVIEW_MODE: "הכנס למצב ביקורת",
    EXIT_REVIEW_MODE: "צא ממצב ביקורת",
    CONFIRM_ENTER_REVIEW_MODE: "האם אתה בטוח שברצונך להכנס למצב ביקורת?",
    CONFIRM_EXIT_REVIEW_MODE: "האם אתה בטוח שברצונך לצאת ממצב ביקורת?",
    REVIEW_MODE_TITLE: "אזהרה! מצב ביקורת פעיל!",
    REVIEW_MODE_MESSAGE: "יום הפעולה עשוי להיות שונה מהנכון, וכן מיילים על טיסות שנחתו לא יישלחו!"
}


export const SUPPORTED_FLIGHT_TYPES : FlightType[] = [
    "Instruction",
    "ClubGuest",
    "MembersGuest",
    "Inspection",
    "Members",
    "InstructorsCourse",
    "Solo"
]

export const SUPPORTED_TOW_TYPES: TowType[] = [
    "AIRPLANE_1500",
    "AIRPLANE_2000",
    "AIRPLANE_2500",
    "AIRPLANE_3000",
    "AIRPLANE_3500",
    "AIRPLANE_4000"
]

export const SUPPORTED_PAYMENT_METHODS: PaymentMethod[] = [
    "Cash",
    "CreditCard",
    "Check",
    "Bit",
]

export const SUPPORTED_PAYERS_TYPES: PayersType[] = [
    "NoPayment",
    "FirstPilot",
    "Guest",
    "BothPilots",
    "SecondPilot",
    "ThirdMember"
]


export const ORDERED_FLIGHT_STATES: FlightState[] = [
    "Draft",
    "Tow",
    "Inflight",
    "Landed",
];
