"""deprecate_instruction_glider

Revision ID: 3e2080d725ff
Revises: fb1c08f3ada1
Create Date: 2023-09-29 13:48:46.090941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e2080d725ff"
down_revision = "fb1c08f3ada1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "actions_instruction_glider_id_fkey", "actions", type_="foreignkey"
    )
    op.drop_column("actions", "instruction_glider_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "actions",
        sa.Column(
            "instruction_glider_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "actions_instruction_glider_id_fkey",
        "actions",
        "gliders",
        ["instruction_glider_id"],
        ["id"],
    )
    # ### end Alembic commands ###
