"""allow_nulls_in_action

Revision ID: 5419af1c3ee8
Revises: 89564245f4fa
Create Date: 2023-09-16 18:34:08.477749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5419af1c3ee8"
down_revision = "89564245f4fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "actions", "field_responsible_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "actions", "responsible_cfi_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "actions", "instruction_glider_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "actions", "instruction_glider_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "actions", "responsible_cfi_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "actions", "field_responsible_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
