"""notifications

Revision ID: 8f84cf0bf889
Revises: b8e743349eee
Create Date: 2023-09-25 10:58:52.601310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8f84cf0bf889"
down_revision = "b8e743349eee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("num_sending_attempts", sa.Integer(), nullable=False),
        sa.Column("last_sending_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("recipient_member_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.drop_index("ix_emails_id", table_name="emails")
    op.drop_table("emails")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emails",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "recipient_member_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("flight_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_id"], ["flights.id"], name="emails_flight_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["recipient_member_id"],
            ["members.id"],
            name="emails_recipient_member_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="emails_pkey"),
    )
    op.create_index("ix_emails_id", "emails", ["id"], unique=False)
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
