"""add_unique_constraint_to_action_date

Revision ID: a8c82b872f74
Revises: dcc330d3c4f3
Create Date: 2025-01-10 16:12:53.684306

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "a8c82b872f74"
down_revision = "dcc330d3c4f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "actions", ["date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "actions", type_="unique")
    # ### end Alembic commands ###
