"""unique_active_tow_airplane

Revision ID: a936f8976e5b
Revises: fea0fbaf51a9
Create Date: 2023-09-27 20:18:36.137792

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "a936f8976e5b"
down_revision = "fea0fbaf51a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_action_airplane", "active_tow_airplanes", ["action_id", "airplane_id"]
    )
    op.create_unique_constraint(
        "unique_action_tow_pilot", "active_tow_airplanes", ["action_id", "tow_pilot_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_action_tow_pilot", "active_tow_airplanes", type_="unique"
    )
    op.drop_constraint("unique_action_airplane", "active_tow_airplanes", type_="unique")
    # ### end Alembic commands ###
