"""tow_release_time

Revision ID: b8e743349eee
Revises: db4503f2e91a
Create Date: 2023-09-25 09:54:41.629091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8e743349eee"
down_revision = "db4503f2e91a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flights", sa.Column("tow_release_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flights", "tow_release_at")
    # ### end Alembic commands ###
