"""events_notifications_traceback

Revision ID: cc263ebd9333
Revises: f4e0463d3326
Create Date: 2024-07-19 17:52:40.814540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc263ebd9333"
down_revision = "f4e0463d3326"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("traceback", sa.String(), nullable=True))
    op.add_column("notifications", sa.Column("traceback", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "traceback")
    op.drop_column("events", "traceback")
    # ### end Alembic commands ###
