"""emails_extra_content

Revision ID: de135e25c5d6
Revises: b8e743349eee
Create Date: 2023-09-25 10:09:46.115376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de135e25c5d6"
down_revision = "b8e743349eee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emails", sa.Column("num_sending_attempts", sa.Integer(), nullable=False)
    )
    op.add_column(
        "emails", sa.Column("last_sending_attempt_at", sa.DateTime(), nullable=True)
    )
    op.add_column("emails", sa.Column("content", sa.Text(), nullable=False))
    op.alter_column(
        "emails", "sent_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_constraint("emails_flight_id_fkey", "emails", type_="foreignkey")
    op.drop_column("emails", "flight_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emails",
        sa.Column("flight_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "emails_flight_id_fkey", "emails", "flights", ["flight_id"], ["id"]
    )
    op.alter_column(
        "emails", "sent_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("emails", "content")
    op.drop_column("emails", "last_sending_attempt_at")
    op.drop_column("emails", "num_sending_attempts")
    # ### end Alembic commands ###
