import { components } from "./api.ts"

export type FlightSchema = components["schemas"]["FlightSchema"]
export type ActionSchema = components["schemas"]["ActionSchema"]
export type MemberSchema = components["schemas"]["MemberSchema"]
export type GliderSchema = components["schemas"]["GliderSchema"]
export type TowAirplaneSchema = components["schemas"]["TowAirplaneSchema"]
export type ActiveTowAirplaneSchema = components["schemas"]["ActiveTowAirplaneSchema"]
export type GliderOwnerSchema = components["schemas"]["GliderOwnerSchema"]
export type MemberRoleSchema = components["schemas"]["MemberRoleSchema"]
export type Role = components["schemas"]["Role"]
export type FlightType = components["schemas"]["FlightType"]
export type TowType = components["schemas"]["TowType"]
export type PayersType = components["schemas"]["PayersType"]
export type PaymentMethod = components["schemas"]["PaymentMethod"]
export type FlightState = components["schemas"]["FlightState"]
export type FlightCreateSchema = components["schemas"]["FlightCreateSchema"]
